language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx

env:
  - 
  - CC=clang CXX=clang++ npm_config_clang=1


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
    export DISPLAY=:99.0;
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16;
    fi

addons:
  apt:
    packages:
      - clang-3.3
      - libx11-dev
      - libxkbfile-dev

script: 'npm test'

git:
  depth: 1

notifications:
  email:
    on_success: never
    on_failure: change
